version: "0.0.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  app:
    container_name: sandbox
    restart: always
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo